### ISSUE TITLE
`bash: $grouplist: ambiguous redirect`

### ISSUE THREAD

**Issue by shivams** [Bash-it/bash-it-docker#1]
I am trying out bash-it using its Docker container, on my Ubuntu 16.04. All works fine, except when I ask for help on plugins using `bash-it help plugins`, it starts throwing this error:

    bash: $grouplist: ambiguous redirect

This error is printed continuously on the screen for a while, and then finally I press <kbd>Ctrl-C</kbd> after which it shows:

```
[3]+  Stopped                 for gfile in $(cat $grouplist | sort | uniq);
do
    printf '%s\n' "${gfile##*.}:"; cat $gfile; printf '\n'; rm $gfile 2> /dev/null;
done | less

```

**Comment by nwinkler** [comment]
@ellerbrock Any idea about this one?

**Comment by ellerbrock** [comment]
@nwinkler sorry for the late reply, baby coming the next days :)

i tried like @shivams mention to run the command `bash-it help plugins` inside the container and got the same error message. after a bit research i found what is causing the problem here: https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash#L384

`mktemp /tmp/grouplist.XXXX` => mktemp: Invalid argument

a fix would be to add 2 more X: `mktemp /tmp/grouplist.XXXXXX`

**Bash Information:**

i start my base image from the latest official bash version (4.4.12(1)-release) from: <https://hub.docker.com/_/bash/>

```
bash --version
GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

Not sure if this have something to do with changes in Bash 4.4 for mktemp?
<https://lists.gnu.org/archive/html/info-gnu/2016-09/msg00012.html>

```
rr. Bash now uses mktemp() when creating internal temporary files; it produces
    a warning at build time on many Linux systems.
```

Cheers Maik

**Comment by nwinkler** [comment]
@ellerbrock Thanks for the fix, and good luck with the baby!

**Comment by ellerbrock** [comment]
@nwinkler thanks for the wishes, since yesterday i'm a daddy 👶  ❤️

**Comment by nwinkler** [comment]
@ellerbrock That's awesome, congrats! Hope mother and child are alright. Now go get some sleep - you'll need it!

**Comment by ellerbrock** [comment]
thanks, yes both are up and running.
can't wait till my daughter is ready to use a keyboard 😃

**Comment by nwinkler** [comment]
Very cute - well done!
